require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EstimateItemsController do

  # This should return the minimal set of attributes required to create a valid
  # EstimateItem. As you add validations to EstimateItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "estimate_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstimateItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all estimate_items as @estimate_items" do
      estimate_item = EstimateItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:estimate_items).should eq([estimate_item])
    end
  end

  describe "GET show" do
    it "assigns the requested estimate_item as @estimate_item" do
      estimate_item = EstimateItem.create! valid_attributes
      get :show, {:id => estimate_item.to_param}, valid_session
      assigns(:estimate_item).should eq(estimate_item)
    end
  end

  describe "GET new" do
    it "assigns a new estimate_item as @estimate_item" do
      get :new, {}, valid_session
      assigns(:estimate_item).should be_a_new(EstimateItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested estimate_item as @estimate_item" do
      estimate_item = EstimateItem.create! valid_attributes
      get :edit, {:id => estimate_item.to_param}, valid_session
      assigns(:estimate_item).should eq(estimate_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EstimateItem" do
        expect {
          post :create, {:estimate_item => valid_attributes}, valid_session
        }.to change(EstimateItem, :count).by(1)
      end

      it "assigns a newly created estimate_item as @estimate_item" do
        post :create, {:estimate_item => valid_attributes}, valid_session
        assigns(:estimate_item).should be_a(EstimateItem)
        assigns(:estimate_item).should be_persisted
      end

      it "redirects to the created estimate_item" do
        post :create, {:estimate_item => valid_attributes}, valid_session
        response.should redirect_to(EstimateItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estimate_item as @estimate_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        EstimateItem.any_instance.stub(:save).and_return(false)
        post :create, {:estimate_item => { "estimate_id" => "invalid value" }}, valid_session
        assigns(:estimate_item).should be_a_new(EstimateItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EstimateItem.any_instance.stub(:save).and_return(false)
        post :create, {:estimate_item => { "estimate_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested estimate_item" do
        estimate_item = EstimateItem.create! valid_attributes
        # Assuming there are no other estimate_items in the database, this
        # specifies that the EstimateItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EstimateItem.any_instance.should_receive(:update).with({ "estimate_id" => "1" })
        put :update, {:id => estimate_item.to_param, :estimate_item => { "estimate_id" => "1" }}, valid_session
      end

      it "assigns the requested estimate_item as @estimate_item" do
        estimate_item = EstimateItem.create! valid_attributes
        put :update, {:id => estimate_item.to_param, :estimate_item => valid_attributes}, valid_session
        assigns(:estimate_item).should eq(estimate_item)
      end

      it "redirects to the estimate_item" do
        estimate_item = EstimateItem.create! valid_attributes
        put :update, {:id => estimate_item.to_param, :estimate_item => valid_attributes}, valid_session
        response.should redirect_to(estimate_item)
      end
    end

    describe "with invalid params" do
      it "assigns the estimate_item as @estimate_item" do
        estimate_item = EstimateItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EstimateItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimate_item.to_param, :estimate_item => { "estimate_id" => "invalid value" }}, valid_session
        assigns(:estimate_item).should eq(estimate_item)
      end

      it "re-renders the 'edit' template" do
        estimate_item = EstimateItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EstimateItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimate_item.to_param, :estimate_item => { "estimate_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estimate_item" do
      estimate_item = EstimateItem.create! valid_attributes
      expect {
        delete :destroy, {:id => estimate_item.to_param}, valid_session
      }.to change(EstimateItem, :count).by(-1)
    end

    it "redirects to the estimate_items list" do
      estimate_item = EstimateItem.create! valid_attributes
      delete :destroy, {:id => estimate_item.to_param}, valid_session
      response.should redirect_to(estimate_items_url)
    end
  end

end
